In [7]:
import numpy as np

Cross Product 

In [ ]:
u = np.array([1, 20, 30])
v = np.array([1, 2, 3])

In [18]:
def vector_vector_multip(u, v):
    assert u.shape[0] == v.shape[0]
    result = 0.0
    for i in range(u.shape[0]):
        result += (u[i] * v[i])
    return result

In [ ]:
vector_vector_multip(u, v)

Dot Product

In [ ]:
u.dot(v)

Matrix U * Vector v

Formula = [(v1 * U11) + (v1 * U12) +  (v1 * U12) + .... + (v1 * U1n), ...]

Code

In [ ]:
def matrix_by_vector(u, v):


In [15]:
v = np.array([2,4,5,6])

U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [13]:
U.shape

(3, 4)

In [16]:
def vector_by_matrix(U, v):
    assert U.shape[1] == v.shape[0]

    rows = U.shape[0]

    result = np.zeros(rows)

    for i in range(rows):
        result[i] = vector_vector_multip(U[i], v)

    return result

In [ ]:
vector_by_matrix(U, v)

Martix Matrix

In [25]:
V = np.array([
[1,2,3],
[5,6,7],
[8,9,10],
[11,12,13]
])

In [22]:
U[:, 1]

array([4, 2, 1])

In [28]:
def matrix_by_matrix (U, V):
    assert U.shape[1] == V.shape[0]

    rows = U.shape[0]
    cols = V.shape[1]

    result = np.zeros((rows, cols))
    
    for i in range(rows):
        vi = V[:, i]
        result[:, i] = vector_by_matrix(U , vi)
        print(result)
    return result
    

In [29]:
matrix_by_matrix(U, V)

[[128.   0.   0.]
 [ 41.   0.   0.]
 [ 35.   0.   0.]]
[[128. 145.   0.]
 [ 41.  47.   0.]
 [ 35.  42.   0.]]
[[128. 145. 162.]
 [ 41.  47.  53.]
 [ 35.  42.  49.]]


array([[128., 145., 162.],
       [ 41.,  47.,  53.],
       [ 35.,  42.,  49.]])