In [1]:
import numpy as np

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

np.full(10, 2)

In [6]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
10 * (np.arange(2, 10) **2) + .5

array([ 40.5,  90.5, 160.5, 250.5, 360.5, 490.5, 640.5, 810.5])

In [13]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [36]:
np.arange(2, 10) > 2

array([False,  True,  True,  True,  True,  True,  True,  True])

In [46]:
np.arange(2, 10).mean()

np.float64(5.5)

In [48]:
np.arange(20, 50).std()

np.float64(8.65544144839919)

Multi Dimensional Array

In [14]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [25]:
n = np.array([
    [1, 20, 30],
    [10, 2, 32],
    [10, 20, 30],
])

In [27]:
n[:, 2]

array([30, 32, 30])

n[2:,]

RANDOM

In [30]:
np.random.rand(5, 2)

array([[0.30568815, 0.57932222],
       [0.35670778, 0.58785571],
       [0.58964746, 0.46214468],
       [0.78425792, 0.7200315 ],
       [0.1784198 , 0.88604039]])

In [32]:
100 * np.random.rand(5, 3)

array([[22.99861295, 83.57806985, 44.31144163],
       [75.5389759 , 86.52079583, 38.95161116],
       [83.4150276 , 82.26231571, 15.04324651],
       [83.67700691, 46.46411567, 64.56463694],
       [22.37618246,  0.72493862, 99.49955049]])

np.random.randint(low=0, high=200, size=(5,3))

Cross Product 

In [54]:
u = np.array([1, 20, 30])
v = np.array([1, 2, 3])

In [59]:
def vector_vector_multip(u, v):
    assert u.shape[0] == v.shape[0]
    result = 0.0
    for i in range(u.shape[0]):
        result += (u[i] * v[i])
    return result
        

In [62]:
vector_vector_multip(u, v)

np.float64(131.0)

In [64]:
u.dot(v)

np.int64(131)